FROM openjdk:17
WORKDIR /app
COPY . /app
RUN javac adda/vit/regno22mic0090/mic0084/mic0119/railwayticketreservation/*.java
CMD ["java", "adda.vit.regno22mic0090.mic0084.mic0119.railwayticketreservation.RailwayTicketReservation"]
